import { Language } from '../types';

const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    'appTitle': "Vedant's EduQuest",
    'appHeaderEmoji': '🔬',
    'appHeaderText': 'EduQuest',
    'appSubtitle': 'Prepare smarter. Teach better.',
    'studentAppSubtitle': 'Your journey to mastery begins.',
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'close': 'Close',
    'view': 'View',
    'import': 'Import',
    'export': 'Export',
    'search': 'Search...',
    'loading': 'Loading...',
    'generating': 'Generating...',
    'undo': 'Undo',
    'redo': 'Redo',
    'copy': 'Copy',
    'sources': 'Sources',
    'profile': 'Profile',
    'board': 'Board',
    'remove': 'Remove',
    'subject': 'Subject',
    
    // Auth
    'phone': 'Phone',
    'phoneNumber': '10-digit Mobile Number',
    'sendOTP': 'Send OTP',
    'enterOTP': 'Enter the 6-digit code',
    'verifyAndSignIn': 'Verify & Sign In',
    'otpSentSuccess': 'An OTP has been sent to your phone.',
    'changePhoneNumber': 'Change number',
    'invalidPhoneNumber': "Please enter a valid 10-digit Indian mobile number.",

    // Tabs
    'bank': 'Question Bank',
    'generator': 'Paper Generator',
    'archive': 'Exam Archive',
    'ai_tutor': 'AI Tutor',
    'settings': 'Settings',

    // Question Fields
    'class': 'Class',
    'chapter': 'Chapter',
    'questionText': 'Question Text',
    'marks': 'Marks',
    'difficulty': 'Difficulty',
    'semester': 'Semester',
    'year': 'Year',
    'source': 'Source',
    'Manual': 'From Bank',
    'Generated': 'AI Generated',
    'Upload': 'Uploaded',
    'Scan': 'Scanned',


    // Difficulty
    'Easy': 'Easy',
    'Moderate': 'Moderate',
    'Hard': 'Hard',

    // Question Bank
    'noQuestions': 'No questions found. Add one to get started!',
    'addQuestion': 'Add New Question',
    'editQuestion': 'Edit Question',
    'allChapters': 'All Chapters',
    'uploadPDF': 'Upload PDF',
    'uploadCSV': 'Upload CSV',

    // Paper Generator
    'generatePaper': 'Generate Paper',
    'paperTitle': 'Paper Title',
    'markDistribution': 'Mark Distribution',
    'avoidPrevious': 'Avoid previous questions',
    'generateAnswersForAI': 'Generate answers (for AI)',
    'useSearchGrounding': 'Use Google Search for latest info',
    'generateWithAI': 'Generate with AI',
    'generate': 'Generate',
    'preview': 'Preview',
    'paperPreview': 'Paper Preview',
    'answerKey': 'Answer Key',
    'exportPDF': 'Export as PDF',
    'exportXLSX': 'Export as XLSX',
    'exportCSV': 'Export as CSV',
    'exportTXT': 'Export as Text',
    'chapterForAI': 'Chapters (comma-separated, e.g., Cell, Genetics)',
    'keywordsForAI': 'Keywords (e.g., mitosis, DNA replication)',
    'questionTypeForAI': 'Question Type (for AI)',
    'selectQuestionType': 'Select a question type...',
    'Short Answer': 'Short Answer',
    'Multiple Choice': 'Multiple Choice',
    'Fill in the Blanks': 'Fill in the Blanks',
    'True/False': 'True/False',
    'Image-based': 'Image-based',
    'Odd Man Out': 'Odd Man Out',
    'Matching': 'Matching',
    'wbbseSyllabusOnly': 'WB Syllabus Only (WBBSE/WBCHSE)',
    'saveDraft': 'Save Draft',
    'clearDraft': 'Clear Draft',
    'clearAISettings': 'Clear AI Settings',
    'aiSettingsCleared': 'AI settings have been cleared.',
    'generateBy': 'Generate by',
    'markDistributionMode': 'Mark Distribution',
    'totalMarksMode': 'Total Marks',
    'totalMarks': 'Total Marks',
    'allowedQuestionMarks': 'Allowed Marks (e.g., 1,2,5)',
    'autoCalculated': 'auto-calculated',
    'distributionGenerationFailed': 'Could not create a paper for the given total marks. Try adjusting total/allowed marks or use Mark Distribution mode.',
    'fallbackToBank': 'AI generation failed. Attempting to generate from your question bank as a fallback.',
    'fallbackSuccess': 'Fallback successful! Paper generated from your question bank.',
    'curriculumSelection': 'Curriculum Selection',
    'selectBoard': 'Select Board',
    'addQuestionType': 'Add Question Type',
    'paperDetails': 'Paper Details',
    // FIX: Removed duplicate key 'numberOfQuestions'. The other instance with 'Number of Questions' will be used.
    // FIX: Removed duplicate key 'marksPerQuestion'. The other instance with 'Marks Per Question' will be used.
    'fetchingChapters': 'Fetching available chapters...',
    'selectChapterForAI': "Chapters for AI Generation",
    'addChapterPlaceholder': "Type or select a chapter to add...",

    // Archive
    'noPapers': 'No papers in the archive.',
    'expandAll': 'Expand All',
    'collapseAll': 'Collapse All',
    'uploadNewPaper': 'Upload New Paper',
    'selectFilesAndUpload': 'Select Files & Upload',
    'fileUploadProgress': 'File Upload Progress',
    'processingFiles': 'Processing Files...',
    'totalFiles': 'Total',
    'completed': 'Completed',
    'pending': 'Pending',
    'currentlyProcessing': 'Processing',

    // Settings
    'dataManagement': 'Data Management',
    'exportData': 'Export All Data',
    'importData': 'Import Data',
    'importWarning': 'This will overwrite all current data.',
    'clearData': 'Clear All Data',
    'clearWarning': 'Are you sure? This action cannot be undone.',
    'appInfo': 'App Information',
    'version': 'Version 1.0',
    'credits': 'Designed and Devloped by Seamate',
    'designedFor': "'Specially Build for all the respected Teachers of W.B.'",
    'studentDesignedFor': "'Specially Build for all the Students of W.B.'",
    'apiKeyManagement': 'Google Gemini API Key',
    'apiKeyInstruction': 'To avoid public usage quotas and ensure reliable access, you can use your own Google AI Gemini API key.',
    'getYourKey': 'Get your key from Google AI Studio.',
    'enterApiKey': 'Enter your Gemini API Key',
    'saveKey': 'Save Key',
    'removeKey': 'Remove Key',
    'openaiApiKeyManagement': 'OpenAI API Key (Fallback)',
    'openaiApiKeyInstruction': 'If the Gemini API fails or exceeds its rate limit, the app can automatically fall back to OpenAI (ChatGPT). Provide your OpenAI API key to enable this feature.',
    'getYourOpenAIKey': 'Get your key from the OpenAI Platform.',
    'enterOpenAIApiKey': 'Enter your OpenAI API Key',
    'supportTitle': 'Support',
    'supportText': 'For any help or inquiries, please contact our support team at:',
    'supportEduQuestTitle': '💬 Support EduQuest',
    'supportEduQuestText': 'EduQuest is a free and premium-quality platform created with care to help teachers and students manage their educational journey easily. If you find this app helpful, your small contribution can make a big difference and help us keep improving EduQuest continuously. 💖',
    'supportUpi': 'UPI: seamate@pnb',
    'supportThankYou': 'Thank you for supporting open, accessible education for everyone! 🙏',
    
    // Student App
    'dashboard': 'Dashboard',
    'results': 'My Results',
    'practice': 'Practice',
    'welcomeStudent': 'Welcome, {name}!',
    'availableTests': 'Available Tests',
    'startTest': 'Start Test',
    'noAvailableTests': "There are no tests available for your class right now. Check back soon!",
    'recentAttempts': 'Recent Attempts',
    'viewResults': 'View Results',
    'scoreLabel': 'Score: {score}/{total}',
    'noAttempts': "You haven't attempted any tests yet. Go ahead and start one!",
    'questionOf': 'Question {current} of {total}',
    'timeRemaining': 'Time Remaining: {time}',
    'next': 'Next',
    'previous': 'Previous',
    'submitTest': 'Submit Test',
    'quitTest': 'Quit Test',
    'quitConfirmation': 'Are you sure you want to quit? Your progress will not be saved.',
    'testResults': 'Test Results',
    'yourScore': 'Your Score',
    'correctAnswer': 'Correct Answer:',
    'yourAnswer': 'Your Answer:',
    'backToResults': 'Back to All Results',
    'testReport': 'Test Report',
    'retakeTest': 'Retake Test',
    'backToDashboard': 'Back to Dashboard',
    'completedOn': 'Completed on',
    'notAttempted': 'Not Attempted',
    'practiceZoneTitle': 'Practice Zone',
    'practiceZoneSubtitle': 'Hone your skills with custom practice sessions.',
    'selectChapter': 'Select a Chapter',
    'selectDifficulty': 'Select Difficulty',
    'allDifficulties': 'All Difficulties',
    'numberOfQuestions': 'Number of Questions',
    'startPractice': 'Start Practice',
    'notEnoughQuestions': "Oops! We couldn't find enough questions for that topic. Try selecting 'All Chapters' or 'All Difficulties' for more options.",
    'getAIAnalysis': 'Get AI Performance Insights',
    'analyzing': 'Analyzing...',
    'performanceAnalysis': 'Performance Analysis',
    'strengths': 'Strengths',
    'weaknesses': 'Areas for Improvement',
    'summary': 'Summary',
    'studySmarter': 'Study Smarter',
    'flashcardGenerator': 'AI Flashcard Generator',
    'generateFlashcards': 'Generate Flashcards',
    'flashcardsFor': 'Flashcards for {chapter}',
    'flip': 'Flip',
    'recommendations': 'AI Recommendations',
    'basedOnLastTest': 'Based on your last test, focus on these areas:',
    'generatingPracticeTest': 'Finding questions and asking our AI tutor to create some fresh ones for you... 🧠',
    'customPracticeSession': 'Custom Practice Session',
    'customPracticeSessionSubtitle': 'Mix questions from the bank with AI-generated ones.',
    'aiMcqChallenge': 'AI MCQ Challenge',
    'aiMcqChallengeSubtitle': 'Create a focused MCQ test on any topic, generated just for you.',
    'selectSemester': 'Select Semester',
    'marksPerQuestion': 'Marks Per Question',
    'startMcqChallenge': 'Start MCQ Challenge',
    'generatingMcqChallenge': 'Crafting your MCQ challenge with AI...',
    'selectChapterForMcq': 'Please select a chapter to generate an MCQ test.',
    'loadingChapters': 'Loading chapters...',
    'selectOrTypeChapter': 'Select or type a chapter...',

    // New Student Practice Features
    'scanYourPaper': 'Scan Your Paper',
    'scanYourPaperSubtitle': 'Take a photo of a question paper to practice it.',
    'scanWithCamera': 'Scan Paper with Camera',
    'analyzingPaper': 'Analyzing paper with AI...',
    'reviewExtractedQuestions': 'Review Extracted Questions',
    'extractedQuestions': 'Extracted Questions',
    'diagramPractice': 'Diagram Practice',
    'diagramPracticeSubtitle': 'Get AI feedback on your hand-drawn diagrams.',
    'suggestDiagrams': 'Suggest Diagrams',
    'suggestingDiagrams': 'AI is finding important diagrams...',
    'importantDiagramsFor': 'Important Diagrams for {chapter}',
    'drawAndUpload': 'Draw this diagram and upload a photo to get it graded.',
    'uploadDrawing': 'Upload Your Drawing',
    'gradingDiagram': 'AI is grading your diagram...',
    'aiTutor': 'AI Tutor',
    'aiTutorSubtitle': 'Stuck on a question? Ask our AI tutor for help.',
    'askYourDoubt': 'Ask Your Doubt',
    'typeYourQuestion': 'Type your question here...',
    'orUploadImage': 'or upload an image of the question',
    'getExplanation': 'Get Explanation',
    'gettingExplanation': 'AI is preparing your explanation...',
    'tutorResponse': 'AI Tutor Response',
    'quickStudyGuide': 'Quick Study Guide',
    'contentType': 'Content Type',
    'definitions': 'Definitions',
    'keyDifferences': 'Key Differences',
    'processExplanations': 'Process Explanations',
    'generateGuide': 'Generate Guide',
    'generatingGuide': 'Generating your study guide...',
    'yourStudyGuide': 'Your Study Guide',

    // New Teacher AI Tools
    'aiTeacherAssistant': 'AI Teacher Assistant',
    'tutorForTeachers': 'AI Tutor for Teachers',
    'tutorForTeachersSubtitle': 'Get lesson ideas, explanations, or answers to complex questions.',
    'askTheTutor': 'Ask the Tutor',
    'yourQuery': 'Your Query',
    'typeYourQueryHere': 'Type a question, topic for a lesson plan, or concept...',


    // Toasts
    'questionAdded': 'Question added successfully!',
    'questionUpdated': 'Question updated successfully!',
    'questionDeleted': 'Question deleted.',
    'paperGenerated': 'Paper generated and automatically saved to archive!',
    'paperDeleted': 'Paper deleted from archive.',
    'dataExported': 'Data exported to eduquest_backup.json.',
    'dataImported': 'Data imported successfully.',
    'dataCleared': 'All data has been cleared.',
    'uploadSuccess': 'File uploaded and added to archive.',
    'ocrError': 'Could not extract text from image.',
    'apiError': 'AI generation failed. Please try again.',
    'apiQuotaError': 'AI generation failed, likely due to API quota limits. Please try again later, or add your own API key in Settings for uninterrupted use.',
    'draftSaved': 'Draft saved successfully!',
    'draftCleared': 'Draft cleared.',
    'draftLoaded': 'Loaded saved draft.',
    'apiKeySaved': 'API Key saved successfully!',
    'apiKeyRemoved': 'API Key removed.',
    'questionCopied': 'Question copied to clipboard!',
    'copyFailed': 'Failed to copy question.',
    'scanningPDF': 'Scanning PDF for questions... This may take a moment.',
    'noQuestionsFromPDF': 'No questions could be extracted from the PDF.',
    'pdfImportSuccess': '{count} questions successfully imported from PDF!',
    'csvImportSuccess': '{count} questions imported from CSV!',
    'csvImportFailed': 'CSV import failed. Check file format or content.',
  },
  bn: {
    'appTitle': "বেদান্তের এডুকোয়েস্ট",
    'appHeaderEmoji': '🔬',
    'appHeaderText': 'এডুকোয়েস্ট',
    'appSubtitle': 'স্মার্টভাবে প্রস্তুতি নিন। ভালোভাবে শেখান।',
    'studentAppSubtitle': 'দক্ষতা অর্জনের পথে আপনার যাত্রা শুরু হোক।',
    'add': 'যোগ করুন',
    'edit': 'সম্পাদনা',
    'delete': 'মুছে ফেলুন',
    'save': 'সংরক্ষণ',
    'cancel': 'বাতিল',
    'close': 'বন্ধ',
    'view': 'দেখুন',
    'import': 'ইম্পোর্ট',
    'export': 'এক্সপোর্ট',
    'search': 'অনুসন্ধান...',
    'loading': 'লোড হচ্ছে...',
    'generating': 'জেনারেট হচ্ছে...',
    'undo': 'পূর্বাবস্থায় ফেরান',
    'redo': 'পুনরায় করুন',
    'copy': 'কপি',
    'sources': 'সূত্র',
    'profile': 'প্রোফাইল',
    'board': 'বোর্ড',
    'remove': 'সরান',
    'subject': 'বিষয়',
    
    'phone': 'ফোন',
    'phoneNumber': '১০-সংখ্যার মোবাইল নম্বর',
    'sendOTP': 'ওটিপি পাঠান',
    'enterOTP': '৬-সংখ্যার কোড লিখুন',
    'verifyAndSignIn': 'যাচাই করুন এবং সাইন ইন করুন',
    'otpSentSuccess': 'আপনার ফোনে একটি ওটিপি পাঠানো হয়েছে।',
    'changePhoneNumber': 'নম্বর পরিবর্তন করুন',
    'invalidPhoneNumber': 'অনুগ্রহ করে একটি বৈধ ১০-সংখ্যার ভারতীয় মোবাইল নম্বর লিখুন।',

    'bank': 'প্রশ্ন ব্যাংক',
    'generator': 'পেপার জেনারেটর',
    'archive': 'পরীক্ষার আর্কাইভ',
    'ai_tutor': 'এআই টিউটর',
    'settings': 'সেটিংস',

    'class': 'শ্রেণী',
    'chapter': 'অধ্যায়',
    'questionText': 'প্রশ্নের পাঠ্য',
    'marks': 'নম্বর',
    'difficulty': 'কঠিনতা',
    'semester': 'সেমিস্টার',
    'year': 'বছর',
    'source': 'উৎস',
    'Manual': 'প্রশ্ন ব্যাংক থেকে',
    'Generated': 'AI দ্বারা তৈরি',
    'Upload': 'আপলোড করা',
    'Scan': 'স্ক্যান করা',

    'Easy': 'সহজ',
    'Moderate': 'মাঝারি',
    'Hard': 'কঠিন',

    'noQuestions': 'কোনো প্রশ্ন পাওয়া যায়নি। শুরু করতে একটি যোগ করুন!',
    'addQuestion': 'নতুন প্রশ্ন যোগ করুন',
    'editQuestion': 'প্রশ্ন সম্পাদনা করুন',
    'allChapters': 'সব অধ্যায়',
    'uploadPDF': 'পিডিএফ আপলোড',
    'uploadCSV': 'সিএসভি আপলোড',

    'generatePaper': 'পেপার জেনারেট করুন',
    'paperTitle': 'পেপারের শিরোনাম',
    'markDistribution': 'নম্বর বন্টন',
    'avoidPrevious': 'পূর্ববর্তী প্রশ্ন এড়িয়ে চলুন',
    'generateAnswersForAI': 'উত্তর জেনারেট করুন (AI এর জন্য)',
    'useSearchGrounding': 'সর্বশেষ তথ্যের জন্য গুগল সার্চ ব্যবহার করুন',
    'generateWithAI': 'AI দিয়ে জেনারেট করুন',
    'generate': 'জেনারেট',
    'preview': 'প্রিভিউ',
    'paperPreview': 'পেপার প্রিভিউ',
    'answerKey': 'উত্তরপত্র',
    'exportPDF': 'পিডিএফ হিসেবে এক্সপোর্ট',
    'exportXLSX': 'এক্সেল হিসেবে এক্সপোর্ট',
    'exportCSV': 'সিএসভি হিসেবে এক্সপোর্ট',
    'exportTXT': 'টেক্সট হিসেবে এক্সপোর্ট',
    'chapterForAI': 'অধ্যায় (কমা দিয়ে আলাদা করুন, যেমন, কোষ, জেনেটিক্স)',
    'keywordsForAI': 'কীওয়ার্ড (যেমন, মাইটোসিস, ডিএনএ রেপ্লিকেশন)',
    'questionTypeForAI': 'প্রশ্নের প্রকার (AI এর জন্য)',
    'selectQuestionType': 'প্রশ্নের প্রকার নির্বাচন করুন...',
    'Short Answer': 'সংক্ষিপ্ত উত্তর',
    'Multiple Choice': 'বহুনির্বাচনী',
    'Fill in the Blanks': 'শূন্যস্থান পূরণ',
    'True/False': 'সত্য/মিথ্যা',
    'Image-based': 'ছবি-ভিত্তিক',
    'Odd Man Out': 'ভিন্নটি খুঁজে বের করো',
    'Matching': 'মিল করো',
    'wbbseSyllabusOnly': 'শুধুমাত্র WB সিলেবাস (WBBSE/WBCHSE)',
    'saveDraft': 'খসড়া সংরক্ষণ করুন',
    'clearDraft': 'খসড়া মুছুন',
    'clearAISettings': 'AI সেটিংস সাফ করুন',
    'aiSettingsCleared': 'AI সেটিংস সাফ করা হয়েছে।',
    'generateBy': 'জেনারেট করুন',
    'markDistributionMode': 'নম্বর বন্টন',
    'totalMarksMode': 'মোট নম্বর',
    'totalMarks': 'মোট নম্বর',
    'allowedQuestionMarks': 'অনুমোদিত নম্বর (যেমন, ১,২,৫)',
    'autoCalculated': 'স্বয়ংক্রিয়ভাবে গণনা করা হয়েছে',
    'distributionGenerationFailed': 'প্রদত্ত মোট নম্বরের জন্য একটি প্রশ্নপত্র তৈরি করা যায়নি। মোট/অনুমোদিত নম্বর পরিবর্তন করার চেষ্টা করুন অথবা নম্বর বন্টন মোড ব্যবহার করুন।',
    'fallbackToBank': 'AI জেনারেশন ব্যর্থ হয়েছে। ফলব্যাক হিসেবে আপনার প্রশ্নব্যাঙ্ক থেকে জেনারেট করার চেষ্টা করা হচ্ছে।',
    'fallbackSuccess': 'ফলব্যাক সফল! আপনার প্রশ্নব্যাঙ্ক থেকে প্রশ্নপত্র তৈরি করা হয়েছে।',
    'curriculumSelection': 'পাঠ্যক্রম নির্বাচন',
    'selectBoard': 'বোর্ড নির্বাচন করুন',
    'addQuestionType': 'প্রশ্নের ধরন যোগ করুন',
    'paperDetails': 'পেপারের বিবরণ',
    'numberOfQuestions': 'প্রশ্নের সংখ্যা',
    'marksPerQuestion': 'প্রতি প্রশ্নে নম্বর',
    'fetchingChapters': 'উপলব্ধ অধ্যায় আনা হচ্ছে...',
    'selectChapterForAI': "AI জেনারেশনের জন্য অধ্যায়",
    'addChapterPlaceholder': "একটি অধ্যায় যোগ করতে টাইপ করুন বা নির্বাচন করুন...",
    
    'noPapers': 'আর্কাইভে কোনো পেপার নেই।',
    'expandAll': 'সব প্রসারিত করুন',
    'collapseAll': 'সব সংকুচিত করুন',
    'uploadNewPaper': 'নতুন পেপার আপলোড করুন',
    'selectFilesAndUpload': 'ফাইল নির্বাচন করুন ও আপলোড করুন',
    'fileUploadProgress': 'ফাইল আপলোড অগ্রগতি',
    'processingFiles': 'ফাইল প্রসেস করা হচ্ছে...',
    'totalFiles': 'মোট',
    'completed': 'সম্পন্ন',
    'pending': 'বাকি',
    'currentlyProcessing': 'প্রসেসিং চলছে',

    'dataManagement': 'ডেটা ম্যানেজমেন্ট',
    'exportData': 'সমস্ত ডেটা এক্সপোর্ট করুন',
    'importData': 'ডেটা ইম্পোর্ট করুন',
    'importWarning': 'এটি সমস্ত বর্তমান ডেটা ওভাররাইট করবে।',
    'clearData': 'সমস্ত ডেটা মুছে ফেলুন',
    'clearWarning': 'আপনি কি নিশ্চিত? এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।',
    'appInfo': 'অ্যাপের তথ্য',
    'version': 'সংস্করণ 1.0',
    'credits': 'ডিজাইন ও ডেভেলপ করেছে Seamate',
    'designedFor': "'বিশেষভাবে পশ্চিমবঙ্গের সমস্ত শ্রদ্ধেয় শিক্ষকদের জন্য নির্মিত।'",
    'studentDesignedFor': "'বিশেষভাবে পশ্চিমবঙ্গের সমস্ত ছাত্রদের জন্য নির্মিত।'",
    'apiKeyManagement': 'Google Gemini API কী',
    'apiKeyInstruction': 'সাধারণ ব্যবহারের কোটা এড়াতে এবং নির্ভরযোগ্য অ্যাক্সেস নিশ্চিত করতে, আপনি নিজের Google AI Gemini API কী ব্যবহার করতে পারেন।',
    'getYourKey': 'Google AI Studio থেকে আপনার কী পান।',
    'enterApiKey': 'আপনার Gemini API কী লিখুন',
    'saveKey': 'কী সংরক্ষণ করুন',
    'removeKey': 'কী সরান',
    'openaiApiKeyManagement': 'OpenAI API কী (ফলব্যাক)',
    'openaiApiKeyInstruction': 'যদি Gemini API ব্যর্থ হয় বা তার রেট সীমা অতিক্রম করে, অ্যাপটি স্বয়ংক্রিয়ভাবে OpenAI (ChatGPT)-তে ফলব্যাক করতে পারে। এই বৈশিষ্ট্যটি সক্রিয় করতে আপনার OpenAI API কী প্রদান করুন।',
    'getYourOpenAIKey': 'OpenAI প্ল্যাটফর্ম থেকে আপনার কী পান।',
    'enterOpenAIApiKey': 'আপনার OpenAI API কী লিখুন',
    'supportTitle': 'সহায়তা',
    'supportText': 'যেকোনো সাহায্য বা অনুসন্ধানের জন্য, আমাদের সহায়তা দলের সাথে যোগাযোগ করুন:',
    'supportEduQuestTitle': '💬 এডুকোয়েস্ট-কে সমর্থন করুন',
    'supportEduQuestText': 'এডুকোয়েস্ট একটি বিনামূল্যে এবং প্রিমিয়াম মানের প্ল্যাটফর্ম যা শিক্ষক এবং শিক্ষার্থীদের তাদের শিক্ষাগত যাত্রা সহজে পরিচালনা করতে সাহায্য করার জন্য যত্ন সহকারে তৈরি করা হয়েছে। যদি আপনি এই অ্যাপটি সহায়ক মনে করেন, আপনার একটি ছোট অবদান একটি বড় পার্থক্য তৈরি করতে পারে এবং আমাদের এডুকোয়েস্ট-কে ক্রমাগত উন্নত করতে সাহায্য করতে পারে। 💖',
    'supportUpi': 'ইউপিআই: seamate@pnb',
    'supportThankYou': 'সবার জন্য উন্মুক্ত, সুলভ শিক্ষাকে সমর্থন করার জন্য আপনাকে ধন্যবাদ! 🙏',

    // Student App
    'dashboard': 'ড্যাশবোর্ড',
    'results': 'আমার ফলাফল',
    'practice': 'অনুশীলন',
    'welcomeStudent': 'স্বাগতম, {name}!',
    'availableTests': 'উপলব্ধ পরীক্ষা',
    'startTest': 'পরীক্ষা শুরু করুন',
    'noAvailableTests': "আপনার শ্রেণীর জন্য এখন কোনো পরীক্ষা উপলব্ধ নেই। শীঘ্রই আবার দেখুন!",
    'recentAttempts': 'সাম্প্রতিক প্রচেষ্টা',
    'viewResults': 'ফলাফল দেখুন',
    'scoreLabel': 'স্কোর: {score}/{total}',
    'noAttempts': "আপনি এখনও কোনো পরীক্ষা দেননি। এগিয়ে যান এবং একটি শুরু করুন!",
    'questionOf': 'প্রশ্ন {current} এর {total}',
    'timeRemaining': 'বাকি সময়: {time}',
    'next': 'পরবর্তী',
    'previous': 'পূর্ববর্তী',
    'submitTest': 'পরীক্ষা জমা দিন',
    'quitTest': 'পরীক্ষা ছাড়ুন',
    'quitConfirmation': 'আপনি কি নিশ্চিতভাবে পরীক্ষা ছাড়তে চান? আপনার অগ্রগতি সংরক্ষিত হবে না।',
    'testResults': 'পরীক্ষার ফলাফল',
    'yourScore': 'আপনার স্কোর',
    'correctAnswer': 'সঠিক উত্তর:',
    'yourAnswer': 'আপনার উত্তর:',
    'backToResults': 'সমস্ত ফলাফলে ফিরে যান',
    'testReport': 'পরীক্ষার রিপোর্ট',
    'retakeTest': 'আবার পরীক্ষা দিন',
    'backToDashboard': 'ড্যাশবোর্ডে ফিরে যান',
    'completedOn': 'সম্পন্ন হয়েছে',
    'notAttempted': 'চেষ্টা করা হয়নি',
    'practiceZoneTitle': 'অনুশীলন ক্ষেত্র',
    'practiceZoneSubtitle': 'কাস্টম অনুশীলন সেশনের মাধ্যমে আপনার দক্ষতা বাড়ান।',
    'selectChapter': 'একটি অধ্যায় নির্বাচন করুন',
    'selectDifficulty': 'কঠিনতা নির্বাচন করুন',
    'allDifficulties': 'সব কঠিনতা',
    // FIX: Removed duplicate key 'numberOfQuestions'.
    'startPractice': 'অনুশীলন শুরু করুন',
    'notEnoughQuestions': "উফ! নির্দিষ্ট বিষয়ের জন্য পর্যাপ্ত প্রশ্ন খুঁজে পাওয়া যায়নি। আরও অনুশীলনের জন্য 'সব অধ্যায়' বা 'সব কঠিনতা' নির্বাচন করে চেষ্টা করুন।",
    'getAIAnalysis': 'AI পারফরম্যান্স ইনসাইট পান',
    'analyzing': 'বিশ্লেষণ করা হচ্ছে...',
    'performanceAnalysis': 'পারফরম্যান্স বিশ্লেষণ',
    'strengths': 'শক্তিশালী দিক',
    'weaknesses': 'উন্নতির ক্ষেত্র',
    'summary': 'সারসংক্ষেপ',
    'studySmarter': 'স্মার্টভাবে অধ্যয়ন করুন',
    'flashcardGenerator': 'AI ফ্ল্যাশকার্ড জেনারেটর',
    'generateFlashcards': 'ফ্ল্যাশকার্ড তৈরি করুন',
    'flashcardsFor': '{chapter} এর জন্য ফ্ল্যাশকার্ড',
    'flip': 'উল্টান',
    'recommendations': 'AI সুপারিশ',
    'basedOnLastTest': 'আপনার শেষ পরীক্ষার উপর ভিত্তি করে, এই ক্ষেত্রগুলিতে ফোকাস করুন:',
    'generatingPracticeTest': 'প্রশ্ন খুঁজছি এবং আপনার জন্য নতুন প্রশ্ন তৈরি করতে আমাদের AI টিউটরকে বলছি... 🧠',
    'customPracticeSession': 'কাস্টম অনুশীলন সেশন',
    'customPracticeSessionSubtitle': 'ব্যাঙ্কের প্রশ্নের সাথে AI-জেনারেটেড প্রশ্ন মিশ্রিত করুন।',
    'aiMcqChallenge': 'AI MCQ চ্যালেঞ্জ',
    'aiMcqChallengeSubtitle': 'যেকোনো বিষয়ে একটি ফোকাসড MCQ পরীক্ষা তৈরি করুন, শুধুমাত্র আপনার জন্য।',
    'selectSemester': 'সেমিস্টার নির্বাচন করুন',
    // FIX: Removed duplicate key 'marksPerQuestion'.
    'startMcqChallenge': 'MCQ চ্যালেঞ্জ শুরু করুন',
    'generatingMcqChallenge': 'AI দিয়ে আপনার MCQ চ্যালেঞ্জ তৈরি করা হচ্ছে...',
    'selectChapterForMcq': 'একটি MCQ পরীক্ষা তৈরি করতে অনুগ্রহ করে একটি অধ্যায় নির্বাচন করুন।',
    'loadingChapters': 'অধ্যায় লোড হচ্ছে...',
    'selectOrTypeChapter': 'একটি অধ্যায় নির্বাচন করুন বা টাইপ করুন...',

    // New Student Practice Features
    'scanYourPaper': 'আপনার প্রশ্নপত্র স্ক্যান করুন',
    'scanYourPaperSubtitle': 'অনুশীলন করার জন্য আপনার প্রশ্নপত্রের একটি ছবি তুলুন।',
    'scanWithCamera': 'ক্যামেরা দিয়ে স্ক্যান করুন',
    'analyzingPaper': 'AI দ্বারা প্রশ্নপত্র বিশ্লেষণ করা হচ্ছে...',
    'reviewExtractedQuestions': 'নিষ্কাশিত প্রশ্ন পর্যালোচনা করুন',
    'extractedQuestions': 'নিষ্কাশিত প্রশ্ন',
    'diagramPractice': 'চিত্র অঙ্কন অনুশীলন',
    'diagramPracticeSubtitle': 'আপনার আঁকা চিত্রের উপর AI থেকে প্রতিক্রিয়া পান।',
    'suggestDiagrams': 'চিত্র প্রস্তাব করুন',
    'suggestingDiagrams': 'AI গুরুত্বপূর্ণ চিত্র খুঁজছে...',
    'importantDiagramsFor': '{chapter}-এর জন্য গুরুত্বপূর্ণ চিত্র',
    'drawAndUpload': 'এই চিত্রটি আঁকুন এবং গ্রেড করার জন্য একটি ছবি আপলোড করুন।',
    'uploadDrawing': 'আপনার আঁকা আপলোড করুন',
    'gradingDiagram': 'AI আপনার চিত্র গ্রেড করছে...',
    'diagramGrade': 'চিত্রের গ্রেড',
    'aiTutor': 'AI শিক্ষক',
    'aiTutorSubtitle': 'কোনো প্রশ্নে আটকে গেছেন? সাহায্যের জন্য আমাদের AI শিক্ষককে জিজ্ঞাসা করুন।',
    'askYourDoubt': 'আপনার সন্দেহ জিজ্ঞাসা করুন',
    'typeYourQuestion': 'আপনার প্রশ্ন এখানে টাইপ করুন...',
    'orUploadImage': 'অথবা প্রশ্নের একটি ছবি আপলোড করুন',
    'getExplanation': 'ব্যাখ্যা পান',
    'gettingExplanation': 'AI আপনার জন্য ব্যাখ্যা প্রস্তুত করছে...',
    'tutorResponse': 'AI শিক্ষকের প্রতিক্রিয়া',
    'quickStudyGuide': 'দ্রুত অধ্যয়নের গাইড',
    'contentType': 'বিষয়বস্তুর প্রকার',
    'definitions': 'সংজ্ঞা',
    'keyDifferences': 'মূল পার্থক্য',
    'processExplanations': 'প্রক্রিয়ার ব্যাখ্যা',
    'generateGuide': 'গাইড তৈরি করুন',
    'generatingGuide': 'আপনার অধ্যয়নের গাইড তৈরি হচ্ছে...',
    'yourStudyGuide': 'আপনার অধ্যয়নের গাইড',

    // New Teacher AI Tools
    'aiTeacherAssistant': 'AI শিক্ষক সহকারী',
    'tutorForTeachers': 'শিক্ষকদের জন্য AI টিউটর',
    'tutorForTeachersSubtitle': 'পাঠ পরিকল্পনা, ধারণা বা জটিল প্রশ্নের উত্তর পান।',
    'askTheTutor': 'টিউটরকে জিজ্ঞাসা করুন',
    'yourQuery': 'আপনার প্রশ্ন',
    'typeYourQueryHere': 'আপনার শিক্ষাগত প্রশ্ন, পাঠ পরিকল্পনার বিষয় বা ধারণার জন্য এখানে টাইপ করুন...',

    'questionAdded': 'প্রশ্ন সফলভাবে যোগ করা হয়েছে!',
    'questionUpdated': 'প্রশ্ন সফলভাবে আপডেট করা হয়েছে!',
    'questionDeleted': 'প্রশ্ন মুছে ফেলা হয়েছে।',
    'paperGenerated': 'পেপার জেনারেট হয়েছে এবং স্বয়ংক্রিয়ভাবে আর্কাইভে সংরক্ষিত হয়েছে!',
    'paperDeleted': 'আর্কাইভ থেকে পেপার মুছে ফেলা হয়েছে।',
    'dataExported': 'ডেটা eduquest_backup.json-এ এক্সপোর্ট করা হয়েছে।',
    'dataImported': 'ডেটা সফলভাবে ইম্পোর্ট করা হয়েছে।',
    'dataCleared': 'সমস্ত ডেটা মুছে ফেলা হয়েছে।',
    'uploadSuccess': 'ফাইল আপলোড হয়েছে এবং আর্কাইভে যোগ করা হয়েছে।',
    'ocrError': 'ছবি থেকে পাঠ্য নিষ্কাশন করা যায়নি।',
    'apiError': 'AI জেনারেশন ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    'apiQuotaError': 'AI জেনারেশন ব্যর্থ হয়েছে, সম্ভবত API কোটার সীমার কারণে। অনুগ্রহ করে পরে আবার চেষ্টা করুন, অথবা নিরবচ্ছিন্ন ব্যবহারের জন্য সেটিংসে আপনার নিজের API কী যোগ করুন।',
    'draftSaved': 'খসড়া সফলভাবে সংরক্ষিত হয়েছে!',
    'draftCleared': 'খসড়া মুছে ফেলা হয়েছে।',
    'draftLoaded': 'সংরক্ষিত খসড়া লোড করা হয়েছে।',
    'apiKeySaved': 'API কী সফলভাবে সংরক্ষিত হয়েছে!',
    'apiKeyRemoved': 'API কী সরানো হয়েছে।',
    'questionCopied': 'প্রশ্ন ক্লিপবোর্ডে কপি করা হয়েছে!',
    'copyFailed': 'প্রশ্ন কপি করতে ব্যর্থ হয়েছে।',
    'scanningPDF': 'পিডিএফ থেকে প্রশ্ন স্ক্যান করা হচ্ছে... এটি কিছু সময় নিতে পারে।',
    'noQuestionsFromPDF': 'পিডিএফ থেকে কোনো প্রশ্ন বের করা যায়নি।',
    'pdfImportSuccess': 'পিডিএফ থেকে {count}টি প্রশ্ন সফলভাবে আমদানি করা হয়েছে!',
    'csvImportSuccess': 'সিএসভি থেকে {count}টি প্রশ্ন সফলভাবে আমদানি করা হয়েছে!',
    'csvImportFailed': 'সিএসভি আমদানি ব্যর্থ হয়েছে। ফাইলের ফর্ম্যাট বা বিষয়বস্তু পরীক্ষা করুন।',
  },
  hi: {
    'appTitle': 'वेदांत का एडुक्वेस्ट',
    'appHeaderEmoji': '🔬',
    'appHeaderText': 'एडुक्वेस्ट',
    'appSubtitle': 'स्मार्ट तैयारी करें। बेहतर सिखाएं।',
    'studentAppSubtitle': 'निपुणता की ओर आपकी यात्रा यहाँ से शुरू होती है।',
    'add': 'जोड़ें',
    'edit': 'संपादित करें',
    'delete': 'हटाएं',
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'close': 'बंद करें',
    'view': 'देखें',
    'import': 'आयात',
    'export': 'निर्यात',
    'search': 'खोजें...',
    'loading': 'लोड हो रहा है...',
    'generating': 'उत्पन्न हो रहा है...',
    'undo': 'पूर्ववत् करें',
    'redo': 'पुनः करें',
    'copy': 'कॉपी',
    'sources': 'स्रोत',
    'profile': 'प्रोफ़ाइल',
    'board': 'बोर्ड',
    'remove': 'हटाएं',
    'subject': 'विषय',
    
    'phone': 'फ़ोन',
    'phoneNumber': '१०-अंकीय मोबाइल नंबर',
    'sendOTP': 'ओटीपी भेजें',
    'enterOTP': '6-अंकीय कोड दर्ज करें',
    'verifyAndSignIn': 'सत्यापित करें और साइन इन करें',
    'otpSentSuccess': 'आपके फ़ोन पर एक ओटीपी भेजा गया है।',
    'changePhoneNumber': 'नंबर बदलें',
    'invalidPhoneNumber': 'कृपया एक वैध १०-अंकीय भारतीय मोबाइल नंबर दर्ज करें।',

    'bank': 'प्रश्न बैंक',
    'generator': 'पेपर जेनरेटर',
    'archive': 'परीक्षा संग्रह',
    'ai_tutor': 'एआई ट्यूटर',
    'settings': 'सेटिंग्स',

    'class': 'कक्षा',
    'chapter': 'अध्याय',
    'questionText': 'प्रश्न का पाठ',
    'marks': 'अंक',
    'difficulty': 'कठिनाई',
    'semester': 'सेमेस्टर',
    'year': 'वर्ष',
    'source': 'स्रोत',
    'Manual': 'प्रश्न बैंक से',
    'Generated': 'एआई द्वारा उत्पन्न',
    'Upload': 'अपलोड किया हुआ',
    'Scan': 'स्कैन किया हुआ',

    'Easy': 'आसान',
    'Moderate': 'मध्यम',
    'Hard': 'कठिन',

    'noQuestions': 'कोई प्रश्न नहीं मिला। आरंभ करने के लिए एक जोड़ें!',
    'addQuestion': 'नया प्रश्न जोड़ें',
    'editQuestion': 'प्रश्न संपादित करें',
    'allChapters': 'सभी अध्याय',
    'uploadPDF': 'पीडीएफ़ अपलोड करें',
    'uploadCSV': 'सीएसवी अपलोड करें',
    
    'generatePaper': 'पेपर उत्पन्न करें',
    'paperTitle': 'पेपर का शीर्षक',
    'markDistribution': 'अंक वितरण',
    'avoidPrevious': 'पिछले प्रश्नों से बचें',
    'generateAnswersForAI': 'उत्तर उत्पन्न करें (AI के लिए)',
    'useSearchGrounding': 'नवीनतम जानकारी के लिए गूगल खोज का उपयोग करें',
    'generateWithAI': 'AI के साथ उत्पन्न करें',
    'generate': 'उत्पन्न करें',
    'preview': 'पूर्वावलोकन',
    'paperPreview': 'पेपर पूर्वावलोकन',
    'answerKey': 'उत्तर कुंजी',
    'exportPDF': 'पीडीएफ में निर्यात करें',
    'exportXLSX': 'एक्सेल में निर्यात करें',
    'exportCSV': 'सीएसवी में निर्यात करें',
    'exportTXT': 'टेक्स्ट में निर्यात करें',
    'chapterForAI': 'अध्याय (अल्पविराम से अलग, जैसे, कोशिका, आनुवंशिकी)',
    'keywordsForAI': 'कीवर्ड (जैसे, माइटोसिस, डीएनए प्रतिकृति)',
    'questionTypeForAI': 'प्रश्न प्रकार (AI के लिए)',
    'selectQuestionType': 'प्रश्न का प्रकार चुनें...',
    'Short Answer': 'संक्षिप्त उत्तर',
    'Multiple Choice': 'बहुविकल्पीय',
    'Fill in the Blanks': 'रिक्त स्थान भरें',
    'True/False': 'सही/गलत',
    'Image-based': 'छवि-आधारित',
    'Odd Man Out': 'विषम चुनें',
    'Matching': 'मिलान करें',
    'wbbseSyllabusOnly': 'केवल WB सिलेबस (WBBSE/WBCHSE)',
    'saveDraft': 'ड्राफ्ट सहेजें',
    'clearDraft': 'ड्राफ्ट साफ़ करें',
    'clearAISettings': 'AI सेटिंग्स साफ़ करें',
    'aiSettingsCleared': 'AI सेटिंग्स साफ़ कर दी गई हैं।',
    'generateBy': 'इसके द्वारा उत्पन्न करें',
    'markDistributionMode': 'अंक वितरण',
    'totalMarksMode': 'कुल अंक',
    'totalMarks': 'कुल अंक',
    'allowedQuestionMarks': 'अनुमत अंक (जैसे, 1,2,5)',
    'autoCalculated': 'स्वतः गणना',
    'distributionGenerationFailed': 'दिए गए कुल अंकों के लिए प्रश्नपत्र नहीं बनाया जा सका। कुल/अनुमत अंकों को समायोजित करने का प्रयास करें या अंक वितरण मोड का उपयोग करें।',
    'fallbackToBank': 'एआई जनरेशन विफल रहा। फ़ॉलबैक के रूप में आपके प्रश्न बैंक से उत्पन्न करने का प्रयास किया जा रहा है।',
    'fallbackSuccess': 'फ़ॉलबैक सफल! आपके प्रश्न बैंक से प्रश्नपत्र उत्पन्न किया गया।',
    'curriculumSelection': 'पाठ्यक्रम चयन',
    'selectBoard': 'बोर्ड चुनें',
    'addQuestionType': 'प्रश्न प्रकार जोड़ें',
    'paperDetails': 'पेपर का विवरण',
    'numberOfQuestions': 'प्रश्नों की संख्या',
    'marksPerQuestion': 'प्रति प्रश्न अंक',
    'fetchingChapters': 'उपलब्ध अध्याय लाए जा रहे हैं...',
    'selectChapterForAI': "एआई जनरेशन के लिए अध्याय",
    'addChapterPlaceholder': "एक अध्याय जोड़ने के लिए टाइप करें या चुनें...",

    'noPapers': 'संग्रह में कोई पेपर नहीं है।',
    'expandAll': 'सभी को विस्तृत करें',
    'collapseAll': 'सभी को संक्षिप्त करें',
    'uploadNewPaper': 'नया पेपर अपलोड करें',
    'selectFilesAndUpload': 'फ़ाइलें चुनें और अपलोड करें',
    'fileUploadProgress': 'फ़ाइल अपलोड प्रगति',
    'processingFiles': 'फ़ाइलें संसाधित हो रही हैं...',
    'totalFiles': 'कुल',
    'completed': 'पूर्ण',
    'pending': 'लंबित',
    'currentlyProcessing': 'संसाधित हो रहा है',

    'dataManagement': 'डेटा प्रबंधन',
    'exportData': 'सभी डेटा निर्यात करें',
    'importData': 'डेटा आयात करें',
    'importWarning': 'यह सभी मौजूदा डेटा को अधिलेखित कर देगा।',
    'clearData': 'सभी डेटा साफ़ करें',
    'clearWarning': 'क्या आप निश्चित हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
    'appInfo': 'ऐप की जानकारी',
    'version': 'संस्करण 1.0',
    'credits': 'Seamate द्वारा डिज़ाइन और विकसित किया गया',
    'designedFor': "'विशेष रूप से पश्चिम बंगाल के सभी सम्मानित शिक्षकों के लिए निर्मित।'",
    'studentDesignedFor': "'विशेष रूप से पश्चिम बंगाल के सभी छात्रों के लिए निर्मित।'",
    'apiKeyManagement': 'Google Gemini API कुंजी',
    'apiKeyInstruction': 'सार्वजनिक उपयोग कोटा से बचने और विश्वसनीय पहुंच सुनिश्चित करने के लिए, आप अपनी खुद की Google AI Gemini API कुंजी का उपयोग कर सकते हैं।',
    'getYourKey': 'Google AI Studio से अपनी कुंजी प्राप्त करें।',
    'enterApiKey': 'अपनी Gemini API कुंजी दर्ज करें',
    'saveKey': 'कुंजी सहेजें',
    'removeKey': 'कुंजी हटाएं',
    'openaiApiKeyManagement': 'OpenAI API कुंजी (फ़ॉलबैक)',
    'openaiApiKeyInstruction': 'यदि जेमिनी एपीआई विफल हो जाता है या अपनी दर सीमा पार कर जाता है, तो ऐप स्वचालित रूप से ओपनएआई (चैटजीपीटी) पर वापस आ सकता है। इस सुविधा को सक्षम करने के लिए अपनी ओपनएआई एपीआई कुंजी प्रदान करें।',
    'getYourOpenAIKey': 'ओपनएआई प्लेटफॉर्म से अपनी कुंजी प्राप्त करें।',
    'enterOpenAIApiKey': 'अपनी OpenAI API कुंजी दर्ज करें',
    'supportTitle': 'सहायता',
    'supportText': 'किसी भी सहायता या पूछताछ के लिए, कृपया हमारी सहायता टीम से संपर्क करें:',
    'supportEduQuestTitle': '💬 एडुक्वेस्ट का समर्थन करें',
    'supportEduQuestText': 'एडुक्वेस्ट एक मुफ्त और प्रीमियम-गुणवत्ता वाला प्लेटफॉर्म है जिसे शिक्षकों और छात्रों को उनकी शैक्षिक यात्रा को आसानी से प्रबंधित करने में मदद करने के लिए देखभाल के साथ बनाया गया है। यदि आपको यह ऐप उपयोगी लगता है, तो आपका छोटा सा योगदान एक बड़ा अंतर ला सकता है और हमें एडुक्वेस्ट को लगातार बेहतर बनाने में मदद कर सकता है। 💖',
    'supportUpi': 'यूपीआई: seamate@pnb',
    'supportThankYou': 'सभी के लिए खुली, सुलभ शिक्षा का समर्थन करने के लिए धन्यवाद! 🙏',
    
    // Student App
    'dashboard': 'डैशबोर्ड',
    'results': 'मेरे परिणाम',
    'practice': 'अभ्यास',
    'welcomeStudent': 'स्वागत है, {name}!',
    'availableTests': 'उपलब्ध परीक्षण',
    'startTest': 'परीक्षण शुरू करें',
    'noAvailableTests': "आपकी कक्षा के लिए अभी कोई परीक्षण उपलब्ध नहीं है। जल्द ही वापस देखें!",
    'recentAttempts': 'हाल के प्रयास',
    'viewResults': 'परिणाम देखें',
    'scoreLabel': 'स्कोर: {score}/{total}',
    'noAttempts': "आपने अभी तक कोई परीक्षण नहीं किया है। आगे बढ़ें और एक शुरू करें!",
    'questionOf': 'प्रश्न {current} का {total}',
    'timeRemaining': 'शेष समय: {time}',
    'next': 'अगला',
    'previous': 'पिछला',
    'submitTest': 'परीक्षण जमा करें',
    'quitTest': 'परीक्षण छोड़ें',
    'quitConfirmation': 'क्या आप वाकई छोड़ना चाहते हैं? आपकी प्रगति सहेजी नहीं जाएगी।',
    'testResults': 'परीक्षण के परिणाम',
    'yourScore': 'आपका स्कोर',
    'correctAnswer': 'सही जवाब:',
    'yourAnswer': 'आपका जवाब:',
    'backToResults': 'सभी परिणामों पर वापस जाएं',
    'testReport': 'परीक्षण रिपोर्ट',
    'retakeTest': 'पुनः परीक्षण करें',
    'backToDashboard': 'डैशबोर्ड पर वापस',
    'completedOn': 'को पूर्ण हुआ',
    'notAttempted': 'प्रयास नहीं किया गया',
    'practiceZoneTitle': 'अभ्यास क्षेत्र',
    'practiceZoneSubtitle': 'कस्टम अभ्यास सत्रों के साथ अपने कौशल को निखारें।',
    'selectChapter': 'एक अध्याय चुनें',
    'selectDifficulty': 'कठिनाई चुनें',
    'allDifficulties': 'सभी कठिनाइयाँ',
    // FIX: Removed duplicate key 'numberOfQuestions'.
    'startPractice': 'अभ्यास शुरू करें',
    'notEnoughQuestions': "उफ़! उस विषय के लिए पर्याप्त प्रश्न नहीं मिल सके। अधिक विकल्पों के लिए 'सभी अध्याय' या 'सभी कठिनाइयाँ' चुनकर प्रयास करें।",
    'getAIAnalysis': 'एआई प्रदर्शन अंतर्दृष्टि प्राप्त करें',
    'analyzing': 'विश्लेषण हो रहा है...',
    'performanceAnalysis': 'प्रदर्शन विश्लेषण',
    'strengths': 'शक्तियां',
    'weaknesses': 'सुधार के क्षेत्र',
    'summary': 'सारांश',
    'studySmarter': 'स्मार्ट अध्ययन करें',
    'flashcardGenerator': 'एआई फ्लैशकार्ड जेनरेटर',
    'generateFlashcards': 'फ्लैशकार्ड बनाएं',
    'flashcardsFor': '{chapter} के लिए फ्लैशकार्ड',
    'flip': 'पलटें',
    'recommendations': 'एआई सिफारिशें',
    'basedOnLastTest': 'आपके अंतिम परीक्षण के आधार पर, इन क्षेत्रों पर ध्यान केंद्रित करें:',
    'generatingPracticeTest': 'प्रश्न खोज रहे हैं और हमारे एआई ट्यूटर से आपके लिए कुछ नए प्रश्न बनाने के लिए कह रहे हैं... 🧠',
    'customPracticeSession': 'कस्टम अभ्यास सत्र',
    'customPracticeSessionSubtitle': 'बैंक के प्रश्नों को AI-जनित प्रश्नों के साथ मिलाएं।',
    'aiMcqChallenge': 'एआई एमसीक्यू चैलेंज',
    'aiMcqChallengeSubtitle': 'किसी भी विषय पर एक केंद्रित एमसीक्यू परीक्षण बनाएं, जो केवल आपके लिए उत्पन्न हो।',
    'selectSemester': 'सेमेस्टर चुनें',
    // FIX: Removed duplicate key 'marksPerQuestion'.
    'startMcqChallenge': 'एमसीक्यू चैलेंज शुरू करें',
    'generatingMcqChallenge': 'एआई के साथ आपकी एमसीक्यू चुनौती तैयार की जा रही है...',
    'selectChapterForMcq': 'एमसीक्यू परीक्षण उत्पन्न करने के लिए कृपया एक अध्याय चुनें।',
    'loadingChapters': 'अध्याय लोड हो रहे हैं...',
    'selectOrTypeChapter': 'एक अध्याय चुनें या टाइप करें...',

    // New Student Practice Features
    'scanYourPaper': 'अपना पेपर स्कैन करें',
    'scanYourPaperSubtitle': 'अभ्यास करने के लिए प्रश्न पत्र का फोटो लें।',
    'scanWithCamera': 'कैमरे से स्कैन करें',
    'analyzingPaper': 'एआई द्वारा पेपर का विश्लेषण किया जा रहा है...',
    'reviewExtractedQuestions': 'निकाले गए प्रश्नों की समीक्षा करें',
    'extractedQuestions': 'निकाले गए प्रश्न',
    'diagramPractice': 'आरेख अभ्यास',
    'diagramPracticeSubtitle': 'अपने हाथ से बनाए गए आरेखों पर एआई से प्रतिक्रिया प्राप्त करें।',
    'suggestDiagrams': 'आरेख सुझाएं',
    'suggestingDiagrams': 'एआई महत्वपूर्ण आरेख खोज रहा है...',
    'importantDiagramsFor': '{chapter} के लिए महत्वपूर्ण आरेख',
    'drawAndUpload': 'इस आरेख को बनाएं और ग्रेडिंग के लिए एक फोटो अपलोड करें।',
    'uploadDrawing': 'अपनी ड्राइंग अपलोड करें',
    'gradingDiagram': 'एआई आपके आरेख की ग्रेडिंग कर रहा है...',
    'diagramGrade': 'आरेख ग्रेड',
    'aiTutor': 'एआई ट्यूटर',
    'aiTutorSubtitle': 'किसी प्रश्न पर अटक गए? हमारे एआई ट्यूटर से मदद मांगें।',
    'askYourDoubt': 'अपना संदेह पूछें',
    'typeYourQuestion': 'अपना प्रश्न यहां टाइप करें...',
    'orUploadImage': 'या प्रश्न की एक छवि अपलोड करें',
    'getExplanation': 'स्पष्टीकरण प्राप्त करें',
    'gettingExplanation': 'एआई आपका स्पष्टीकरण तैयार कर रहा है...',
    'tutorResponse': 'एआई ट्यूटर की प्रतिक्रिया',
    'quickStudyGuide': 'त्वरित अध्ययन गाइड',
    'contentType': 'सामग्री का प्रकार',
    'definitions': 'परिभाषाएं',
    'keyDifferences': 'मुख्य अंतर',
    'processExplanations': 'प्रक्रिया स्पष्टीकरण',
    'generateGuide': 'गाइड उत्पन्न करें',
    'generatingGuide': 'आपकी अध्ययन मार्गदर्शिका तैयार हो रही है...',
    'yourStudyGuide': 'आपकी अध्ययन मार्गदर्शिका',
    
    // New Teacher AI Tools
    'aiTeacherAssistant': 'एआई शिक्षक सहायक',
    'tutorForTeachers': 'शिक्षकों के लिए एआई ट्यूटर',
    'tutorForTeachersSubtitle': 'पाठ योजना के विचार, स्पष्टीकरण, या जटिल प्रश्नों के उत्तर प्राप्त करें।',
    'askTheTutor': 'ट्यूटर से पूछें',
    'yourQuery': 'आपका प्रश्न',
    'typeYourQueryHere': 'अपना शैक्षणिक प्रश्न, पाठ योजना के लिए विषय, या अवधारणा टाइप करें...',

    'questionAdded': 'प्रश्न सफलतापूर्वक जोड़ा गया!',
    'questionUpdated': 'प्रश्न सफलतापूर्वक अपडेट किया गया!',
    'questionDeleted': 'प्रश्न हटा दिया गया है।',
    'paperGenerated': 'पेपर उत्पन्न हुआ और स्वचालित रूप से संग्रह में सहेजा गया!',
    'paperDeleted': 'संग्रह से पेपर हटा दिया गया।',
    'dataExported': 'डेटा eduquest_backup.json में निर्यात किया गया।',
    'dataImported': 'डेटा सफलतापूर्वक आयात किया गया।',
    'dataCleared': 'सभी डेटा साफ़ कर दिया गया है।',
    'uploadSuccess': 'फ़ाइल अपलोड हुई और संग्रह में जोड़ी गई।',
    'ocrError': 'छवि से पाठ नहीं निकाला जा सका।',
    'apiError': 'AI उत्पादन विफल रहा। कृपया पुनः प्रयास करें।',
    'apiQuotaError': 'AI उत्पादन विफल रहा, संभवतः API कोटा सीमा के कारण। कृपया बाद में पुनः प्रयास करें, या निर्बाध उपयोग के लिए सेटिंग्स में अपनी API कुंजी जोड़ें।',
    'draftSaved': 'ड्राफ्ट सफलतापूर्वक सहेजा गया!',
    'draftCleared': 'ड्राफ्ट साफ़ हो गया।',
    'draftLoaded': 'सहेजा गया ड्राफ्ट लोड किया गया।',
    'apiKeySaved': 'एपीआई कुंजी सफलतापूर्वक सहेजी गई!',
    'apiKeyRemoved': 'एपीआई कुंजी हटा दी गई है।',
    'questionCopied': 'प्रश्न क्लिपबोर्ड पर कॉपी किया गया!',
    'copyFailed': 'प्रश्न कॉपी करने में विफल।',
    'scanningPDF': 'पीडीएफ़ से प्रश्न स्कैन किए जा रहे हैं... इसमें कुछ समय लग सकता है।',
    'noQuestionsFromPDF': 'पीडीएफ़ से कोई प्रश्न नहीं निकाला जा सका।',
    'pdfImportSuccess': 'पीडीएफ़ से {count} प्रश्न सफलतापूर्वक आयात किए गए!',
    'csvImportSuccess': 'सीएसवी से {count} प्रश्न सफलतापूर्वक आयात किए गए!',
    'csvImportFailed': 'सीएसवी आयात विफल। फ़ाइल प्रारूप या सामग्री की जाँच करें।',
  }
};

export const t = (key: string, lang: Language): string => {
  const translation = translations[lang]?.[key];
  if (translation === undefined) {
    // Fallback to English if the key is not found in the current language
    return translations.en[key] || key;
  }
  return translation;
};